export interface NewsHeadline {
  title: string;
  original_title: string | null;
  source: string | null;
  sentiment_label: "positive" | "neutral" | "negative";
}

export interface DailyReport {
  id: number;
  report_date: string;
  stock_id: number;
  ticker: string;
  name: string;
  current_price: number | null;
  change_rate: number | null;
  recent_5d_flow: string;
  volume_change: number | null;
  positive_factors: string[];
  negative_factors: string[];
  neutral_factors: string[];
  news_summary: string;
  news_positive_count: number;
  news_negative_count: number;
  news_neutral_count: number;
  news_sentiment_score: number;
  news_headlines: NewsHeadline[];
  technical_analysis: string;
  flow_analysis: string;
  up_probability: number;
  down_probability: number;
  expected_range_low: number;
  expected_range_high: number;
  confidence_level: "very_low" | "low" | "medium" | "high";
  key_risks: string;
  user_checklist: string;
  final_view: string;
  final_score: number;
  day1_expected_low: number | null;
  day1_expected_high: number | null;
  day1_expected_price: number | null;
  day1_expected_return: number | null;
  day2_expected_low: number | null;
  day2_expected_high: number | null;
  day2_expected_price: number | null;
  day2_expected_return: number | null;
  sell_target_price: number | null;
  sell_target_return: number | null;
  sell_target_low: number | null;
  sell_target_high: number | null;
  support_price: number | null;
  resistance_price: number | null;
  trailing_stop_percent: number | null;
  sell_strategy: string;
  sell_target_basis: string[];
  direction_signal: string;
  action_signal: string;
  data_status: "available" | "unavailable";
  data_quality_score: number;
  decision_status: "defer" | "buy_watch" | "risk_reduce" | "hold";
  surge_warning: boolean;
  surge_reason: string;
  active_model_version: string;
  raw_up_probability: number | null;
  calibrated_up_probability: number | null;
  validation_sample_count: number;
  probability_bucket_observed_rate: number | null;
  confidence_basis: string[];
  market_regime: string;
  signal_status: "high_confidence_signal" | "defer";
  defer_reason: string;
  created_at: string;
}
